# To calculate yml to json
# http://yaml-online-parser.appspot.com/
---
driver:
  name: vagrant


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
      - recipe[bcs_locale::default]

suites:
  - name: default
    run_list:
      - recipe[bcs_postgresql::default]
    attributes:
      postgresql:
        users:
          - username: richard
            superuser: false
            createdb: true
            login: true
