# To calculate yml to json
# http://yaml-online-parser.appspot.com/
---
driver:
  # keeping vagrant as if anything faster than docker - 2.45 vs 3.10
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: latest # >= 14
  deprecations_as_errors: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[bcs_postgresql::default]
    attributes:
      postgresql:
        users:
          - username: richard
            superuser: false
            createdb: true
            login: true
        password:
          postgres: 'secret'
